version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=lib_school
      - MYSQL_ROOT_PASSWORD=fstack@1234
    volumes:
      - "./db:/var/lib/mysql"
    ports:
      - '3310:3306'
    expose:
      - 3306

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    environment:
      DB_HOST: db
      port: 3306
      username: fstack
